import type { NextPage } from 'next'
import IntroItem from './components/IntroItem';
import Head from 'next/head'
import Image from 'next/image'
import * as Styled from './index.styled';
import Skill from './components/skill';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>fwywd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Styled.Header>
        <Image src="/logo.png" height="100px" width="200px" />
        <Styled.HeaderMenu>
          <Styled.MenuItem href="#about">ABOUT</Styled.MenuItem>
          <Styled.MenuItem href="#skills">SKILLS</Styled.MenuItem>
          <Styled.MenuItem href="#values">VALUES</Styled.MenuItem>
          <Styled.MenuItem href="#future">FUTURE</Styled.MenuItem>
        </Styled.HeaderMenu>
      </Styled.Header>
      <Styled.Title>
        <Styled.MainTitle>メインタイトル</Styled.MainTitle>
        <Styled.SubTitle>サブタイトル</Styled.SubTitle>
      </Styled.Title>
      <Styled.AboutMe>
        <IntroItem title="趣味" text="テキスト"></IntroItem>
        <IntroItem title="好きな食べ物" text="テキスト"></IntroItem>
        <IntroItem title="性格" text="テキスト"></IntroItem>
      </Styled.AboutMe>
      <Skill></Skill>
    </>
  )
}

export default Home
